/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline_management;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPDF;
import db.FlightDb;
import db.FlightDetailsDb;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import model.FlightDetails;
import db.TicketDb;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Flight;
import model.Ticket;

/**
 *
 * @author shreyasdasariicloud.com
 */
public class BookTicket extends javax.swing.JFrame {
    public int id = 1;
    public int grandTotal = 0;
    public int flightPrice = 0;
    public int amount = 0;
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobilePattern = "^[0-9]*$";
    public String userEmail;

    /**
     * Creates new form BookTicket
     */
    public BookTicket() {
        initComponents();   
    }
    public BookTicket(String email) {
        initComponents();
        txtFlightNo.setEditable(false);
        txtPrice.setEditable(false);
        txtTotal.setEditable(false);
        btnBook.setEnabled(false);
        JFormattedTextField tf = ((JSpinner.DefaultEditor) sQuantity.getEditor()).getTextField();
        tf.setEditable(false);
        userEmail = email;
    }
    
    public void flightDetailsFlightNameByFlight(String flightName){
        DefaultTableModel dtm = (DefaultTableModel) tblName.getModel();
        dtm.setRowCount(0);
        ArrayList<FlightDetails> list = FlightDetailsDb.getAllRecordsByCategory(flightName);
        Iterator<FlightDetails> itr = list.iterator();
        while(itr.hasNext()){
            FlightDetails flightDetailsObj = itr.next();
            dtm.addRow(new Object[]{flightDetailsObj.getFlightName()});
        }
    }
    
    public void filterFlightDetailsByFlightName(String flightNo,String flightName){
        DefaultTableModel dtm = (DefaultTableModel) tblName.getModel();
        dtm.setRowCount(0);
        ArrayList<FlightDetails> list = FlightDetailsDb.filterFlightDetailsByName(flightNo,flightName);
        Iterator<FlightDetails> itr = list.iterator();
        while(itr.hasNext()){
            FlightDetails flightDetailsObj = itr.next();
            dtm.addRow(new Object[]{flightDetailsObj.getFlightName()});
        }
    }
    
    public void clear(){
        txtFlightNo.setText("");
        txtPrice.setText("");
        sQuantity.setValue(1);
        txtTotal.setText("");
        btnBook.setEnabled(false);
    }
    
    public void validateFields(){
        String userName = txtUserName.getText();
        String userMobileNo = txtUserMobileNo.getText();
        String userEmail = txtUserEmail.getText();
        if(!userName.equals("") && userMobileNo.matches(mobilePattern) && userMobileNo.length() == 10 && userEmail.matches(emailPattern) && grandTotal > 0)
            btnGenerateTicket.setEnabled(true);
        else
            btnGenerateTicket.setEnabled(false);
            
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTicketID = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblUserDetails = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtUserEmail = new javax.swing.JTextField();
        lblMobileNo = new javax.swing.JLabel();
        txtUserMobileNo = new javax.swing.JTextField();
        lblSource = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        lblDestination = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        lblFlight = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cbFlight = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblName = new javax.swing.JTable();
        lblFlightNo = new javax.swing.JLabel();
        txtFlightNo = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        sQuantity = new javax.swing.JSpinner();
        btnClear = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTotal = new javax.swing.JTable();
        lblGrandTotal = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        btnGenerateTicket = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTitle.setText("Book Ticket");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblTicketID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTicketID.setText("Ticket ID:");
        getContentPane().add(lblTicketID, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 103, -1, -1));

        lblID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblID.setText("--");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 103, -1, -1));

        lblUserDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUserDetails.setText("User Details:");
        getContentPane().add(lblUserDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 142, -1, -1));

        lblName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblName.setText("Name:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 181, -1, -1));

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEmail.setText("Email:");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 259, -1, -1));

        txtUserName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 217, 250, -1));

        txtUserEmail.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtUserEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 295, 250, -1));

        lblMobileNo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblMobileNo.setText("MobileNo:");
        getContentPane().add(lblMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 337, -1, -1));

        txtUserMobileNo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtUserMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserMobileNoKeyReleased(evt);
            }
        });
        getContentPane().add(txtUserMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 373, 250, -1));

        lblSource.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSource.setText("Source:");
        getContentPane().add(lblSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 415, -1, -1));

        txtSource.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 451, 250, -1));

        lblDestination.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblDestination.setText("Destination:");
        getContentPane().add(lblDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 493, -1, -1));

        txtDestination.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 529, 250, -1));

        lblFlight.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFlight.setText("Flight:");
        getContentPane().add(lblFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 103, -1, -1));

        lblSearch.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSearch.setText("Search:");
        getContentPane().add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 181, -1, -1));

        txtSearch.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 217, 250, -1));

        cbFlight.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        cbFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFlightActionPerformed(evt);
            }
        });
        getContentPane().add(cbFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 139, 250, -1));

        tblName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        tblName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        tblName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblName);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 259, 250, -1));

        lblFlightNo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFlightNo.setText("Flight No.:");
        getContentPane().add(lblFlightNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 103, -1, -1));

        txtFlightNo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtFlightNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 139, 250, -1));

        lblPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPrice.setText("Price:");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 103, -1, -1));

        txtPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 139, 250, -1));

        lblQuantity.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblQuantity.setText("Quantity:");
        getContentPane().add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 181, -1, -1));

        lblTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 181, -1, -1));

        txtTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 217, 250, -1));

        sQuantity.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sQuantityStateChanged(evt);
            }
        });
        getContentPane().add(sQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 217, 250, -1));

        btnClear.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 259, -1, -1));

        btnBook.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 259, -1, -1));

        tblTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        tblTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight No.", "Price", "Quantity", "Total"
            }
        ));
        tblTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTotalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTotal);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 301, 566, 385));

        lblGrandTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblGrandTotal.setText("Grand Total:");
        getContentPane().add(lblGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 707, -1, -1));

        lblAmount.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAmount.setText("00");
        getContentPane().add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 707, -1, -1));

        btnGenerateTicket.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnGenerateTicket.setText("Generate Ticket & Print");
        btnGenerateTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateTicketActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(1136, 704, -1, -1));

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 662, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginJFrame().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        id = Integer.parseInt(TicketDb.getID());
        lblID.setText(TicketDb.getID());
        ArrayList<Flight> list = FlightDb.getallRecords();
        Iterator<Flight> itr = list.iterator();
        while(itr.hasNext()){
            Flight flightObj = itr.next();
            cbFlight.addItem(flightObj.getFlightName());
//            txtSource.setText(flightObj.getSource());
//            txtDestination.setText(flightObj.getDestination());
        }
        String Flight = (String) cbFlight.getSelectedItem();
        flightDetailsFlightNameByFlight(Flight);
    }//GEN-LAST:event_formComponentShown

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String name = txtSearch.getText();
        String flight = (String) cbFlight.getSelectedItem();
        filterFlightDetailsByFlightName(name,flight);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNameMouseClicked
        // TODO add your handling code here:
        int index = tblName.getSelectedRow();
        TableModel model = tblName.getModel();
        String flightName = model.getValueAt(index, 0).toString();
        FlightDetails flightDetails = FlightDetailsDb.getFlightDetailsByName(flightName);
        txtFlightNo.setText(flightDetails.getFlightNo());
        txtPrice.setText(flightDetails.getPrice());
        sQuantity.setValue(1);
        txtTotal.setText(flightDetails.getPrice());
        flightPrice = Integer.parseInt(flightDetails.getPrice());
        amount = Integer.parseInt(flightDetails.getPrice());
        btnBook.setEnabled(true);
        
        
    }//GEN-LAST:event_tblNameMouseClicked

    private void sQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sQuantityStateChanged
        // TODO add your handling code here:
        int quantity = (Integer) sQuantity.getValue();
        if(quantity <= 1){
            sQuantity.setValue(1);
            quantity = 1;
        }
        amount = flightPrice * quantity;
        txtTotal.setText(String.valueOf(amount));
    }//GEN-LAST:event_sQuantityStateChanged

    private void cbFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFlightActionPerformed
        // TODO add your handling code here:
        String flightName = (String) cbFlight.getSelectedItem();
        flightDetailsFlightNameByFlight(flightName);
    }//GEN-LAST:event_cbFlightActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        String name = txtFlightNo.getText();
        String price = txtPrice.getText();
        String quantity = String.valueOf(sQuantity.getValue());
        DefaultTableModel dtm = (DefaultTableModel) tblTotal.getModel();
        dtm.addRow(new Object[]{name, price,quantity,amount});
        grandTotal = grandTotal + amount;
        lblAmount.setText(String.valueOf(grandTotal));
        
        clear();
        validateFields();
        
        
    
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void txtUserEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserEmailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtUserEmailKeyReleased

    private void txtUserMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserMobileNoKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtUserMobileNoKeyReleased

    private void btnGenerateTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateTicketActionPerformed
        // TODO add your handling code here:
        String userName = txtUserName.getText();
        String userMobileNo = txtUserMobileNo.getText();
        String UEmail = txtUserEmail.getText();
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String todayDate = dFormat.format(date);
        String total = String.valueOf(grandTotal);
        String createdBy = userEmail;
        Ticket ticket = new Ticket();
        ticket.setId(id);
        ticket.setName(userName);
        ticket.setMobileno(userMobileNo);
        ticket.setEmail(UEmail);
        ticket.setDate(todayDate);
        ticket.setTotal(total);
        ticket.setCreatedBy(createdBy);
        ticket.setSource(source);
        ticket.setDestination(destination);
        TicketDb.save(ticket);
        
        String path = "/Users/shreyasdasariicloud.com/Desktop/";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + id + ".pdf"));
            doc.open();
            Paragraph airlineName = new Paragraph("Alpha Airline Management System");
            doc.add(airlineName);
            Paragraph star = new Paragraph("***************************************************************************************************************");
            doc.add(star);
            Paragraph content = new Paragraph("\tTicket ID:"+id+"\nName:"+userName+"\nSource:"+source+"\nDestination:"+destination+"\nTotal Amount Paid:"+total+"");
            doc.add(content);
            doc.add(star);
            PdfPTable tbl = new PdfPTable(4);
            tbl.addCell("Flight No.");
            tbl.addCell("Price");
            tbl.addCell("Quantity");
            tbl.addCell("Total");
            for (int i = 0; i<tblTotal.getRowCount(); i++){
                String a = tblTotal.getValueAt(i, 0).toString();
                String b = tblTotal.getValueAt(i, 1).toString();
                String c = tblTotal.getValueAt(i, 2).toString();
                String d = tblTotal.getValueAt(i, 3).toString();
                tbl.addCell(a);
                tbl.addCell(b);
                tbl.addCell(c);
                tbl.addCell(d);
                
            }
            doc.add(tbl);
            doc.add(star);
            Paragraph lastLine = new Paragraph("\nThank you for flying with Alpha Airline! Have a safe journey!");
            doc.add(lastLine);
            OpenPDF.openById(String.valueOf(id));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        setVisible(false);
        new BookTicket(createdBy).setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_btnGenerateTicketActionPerformed

    private void tblTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTotalMouseClicked
        // TODO add your handling code here:
        int index = tblTotal.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            TableModel model = tblTotal.getModel();
            String total = model.getValueAt(index, 3).toString();
            grandTotal = grandTotal - Integer.parseInt(total);
            lblGrandTotal.setText(String.valueOf(grandTotal));
            ((DefaultTableModel) tblTotal.getModel()).removeRow(index);
                    
        }
    }//GEN-LAST:event_tblTotalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateTicket;
    private javax.swing.JComboBox<String> cbFlight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFlight;
    private javax.swing.JLabel lblFlightNo;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMobileNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblTicketID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUserDetails;
    private javax.swing.JSpinner sQuantity;
    private javax.swing.JTable tblName;
    private javax.swing.JTable tblTotal;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtFlightNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserMobileNo;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
