/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline_management;

import model.FlightDetails;
import db.FlightDetailsDb;
import db.FlightDb;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Flight;

/**
 *
 * @author shreyasdasariicloud.com
 */
public class EditFlight extends javax.swing.JFrame {

    /**
     * Creates new form EditFlight
     */
    public EditFlight() {
        initComponents();
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    public void validateFields() {
        String flightName = txtFlight.getText();
        String flightNo = (String) cbFlightNo.getSelectedItem();
        String price = txtPrice.getText();
        if (!flightName.equals("") && flightNo != null && !price.equals("")) {
            btnUpdate.setEnabled(true);
        } else {
            btnUpdate.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditFlight = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        lblFlightName = new javax.swing.JLabel();
        lblFlightNo = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtFlight = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cbFlightNo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEdit = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEditFlight.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEditFlight.setText("Edit Flight");
        getContentPane().add(lblEditFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblID1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblID1.setText("ID");
        getContentPane().add(lblID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 191, -1, -1));

        lblFlightName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFlightName.setText("Flight Name");
        getContentPane().add(lblFlightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 241, -1, -1));

        lblFlightNo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFlightNo.setText("Flight No");
        getContentPane().add(lblFlightNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 298, -1, -1));

        lblPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPrice.setText("Price");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 350, -1, -1));

        txtFlight.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtFlight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFlightKeyReleased(evt);
            }
        });
        getContentPane().add(txtFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 238, 260, -1));

        txtPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 347, 260, -1));

        cbFlightNo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        cbFlightNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbFlightNoKeyReleased(evt);
            }
        });
        getContentPane().add(cbFlightNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 295, 260, -1));

        tblEdit.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        tblEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Flight Name", "Flight No", "Price"
            }
        ));
        tblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEdit);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 185, -1, 153));

        btnUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnUpdateComponentShown(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 425, -1, -1));

        btnClear.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 425, -1, -1));

        btnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 425, -1, -1));

        lblID.setText("00");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 192, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("View and Edit Flights");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, -1));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 470, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFlightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFlightKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtFlightKeyReleased

    private void cbFlightNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbFlightNoKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_cbFlightNoKeyReleased

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtPriceKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        FlightDetails flightDetails = new FlightDetails();
        int id = Integer.parseInt(lblID.getText());
        flightDetails.setId(id);
        flightDetails.setFlightName(txtFlight.getText());
        flightDetails.setFlightNo((String) cbFlightNo.getSelectedItem());
        flightDetails.setPrice(txtPrice.getText());
        FlightDetailsDb.update(flightDetails);
        setVisible(false);
        new EditFlight().setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnUpdateComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblEdit.getModel();
        ArrayList<FlightDetails> list = FlightDetailsDb.getAllRecords();
        Iterator<FlightDetails> itr = list.iterator();
        while (itr.hasNext()) {
            FlightDetails flightDetailsObj = itr.next();
            dtm.addRow(new Object[]{flightDetailsObj.getId(), flightDetailsObj.getFlightName(), flightDetailsObj.getFlightNo(), flightDetailsObj.getPrice()});
        }
    }//GEN-LAST:event_formComponentShown

    private void tblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditMouseClicked
        // TODO add your handling code here:
        int index = tblEdit.getSelectedRow();
        TableModel model = tblEdit.getModel();
        String id = model.getValueAt(index, 0).toString();
        lblID.setText(id);
        String flightName = model.getValueAt(index, 1).toString();
        txtFlight.setText(flightName);
        String flightNo = model.getValueAt(index, 2).toString();
        String price = model.getValueAt(index, 3).toString();
        txtPrice.setText(price);

        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        cbFlightNo.removeAllItems();
        cbFlightNo.addItem(flightNo);
        ArrayList<Flight> flightList = FlightDb.getallRecords();
        Iterator<Flight> flightItr = flightList.iterator();
        while (flightItr.hasNext()) {
            Flight flightObj = flightItr.next();
            if (!flightObj.getFlightName().equals(flightNo)) {
                cbFlightNo.addItem(flightObj.getFlightName());
            }
        }

    }//GEN-LAST:event_tblEditMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = lblID.getText();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            FlightDetailsDb.delete(id);
            setVisible(false);
            new EditFlight().setVisible(true);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new EditFlight().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbFlightNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditFlight;
    private javax.swing.JLabel lblFlightName;
    private javax.swing.JLabel lblFlightNo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JTable tblEdit;
    private javax.swing.JTextField txtFlight;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
