/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline_management;

/**
 *
 * @author shreyasdasariicloud.com
 */
public class Enterprise extends javax.swing.JFrame {

    /**
     * Creates new form Enterprise
     */
    public Enterprise() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        btnPassenger = new javax.swing.JButton();
        btnFlightCrew = new javax.swing.JButton();
        btnMedicalEmergency = new javax.swing.JButton();
        btnSecurity = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ALPHA AIRLINE MANAGEMENT");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 585, -1));

        lblEnterprise.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEnterprise.setText("ENTERPRISE:");
        getContentPane().add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, 120, -1));

        btnPassenger.setText("PASSENGER");
        btnPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassengerActionPerformed(evt);
            }
        });
        getContentPane().add(btnPassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 201, 169, -1));

        btnFlightCrew.setText("FLIGHT CREW");
        btnFlightCrew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightCrewActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlightCrew, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 201, 169, -1));

        btnMedicalEmergency.setText("MEDICAL EMERGENCY");
        btnMedicalEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicalEmergencyActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedicalEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 285, -1, -1));

        btnSecurity.setText("SECURITY");
        btnSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecurityActionPerformed(evt);
            }
        });
        getContentPane().add(btnSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 285, 169, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-page-background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassengerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginEnterprise().setVisible(true);
    }//GEN-LAST:event_btnPassengerActionPerformed

    private void btnFlightCrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightCrewActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginEnterprise().setVisible(true);
    }//GEN-LAST:event_btnFlightCrewActionPerformed

    private void btnMedicalEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicalEmergencyActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginEnterprise().setVisible(true);
    }//GEN-LAST:event_btnMedicalEmergencyActionPerformed

    private void btnSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecurityActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginEnterprise().setVisible(true);
    }//GEN-LAST:event_btnSecurityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enterprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enterprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enterprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enterprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enterprise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFlightCrew;
    private javax.swing.JButton btnMedicalEmergency;
    private javax.swing.JButton btnPassenger;
    private javax.swing.JButton btnSecurity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
