/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline_management;
import model.FlightDetails;
import model.Flight;
import db.FlightDb;
import java.util.ArrayList;
import java.util.Iterator;
import db.FlightDetailsDb;

/**
 *
 * @author shreyasdasariicloud.com
 */
public class FlightDetailsProduct extends javax.swing.JFrame {

    /**
     * Creates new form FlightDetails
     */
    public FlightDetailsProduct() {
        initComponents();
        btnSave.setEnabled(false);
    }
    
    public void validateFields(){
        String flightName = txtFlight.getText();
        String price = txtPrice.getText();
        if(!flightName.equals("") && !price.equals(""))
            btnSave.setEnabled(true);
        else
            btnSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFlightDetails = new javax.swing.JLabel();
        lblFlight = new javax.swing.JLabel();
        lblFlightNo = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtFlight = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cbFlightNo = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFlightDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFlightDetails.setText("Flight Details");
        getContentPane().add(lblFlightDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblFlight.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFlight.setText("Flight");
        getContentPane().add(lblFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 108, -1, -1));

        lblFlightNo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFlightNo.setText("Flight No.");
        getContentPane().add(lblFlightNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 150, -1, -1));

        lblPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPrice.setText("Price");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 192, -1, -1));

        txtFlight.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtFlight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFlightKeyReleased(evt);
            }
        });
        getContentPane().add(txtFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 105, 270, -1));

        txtPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 189, 270, -1));

        btnSave.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 264, -1, -1));

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 264, -1, -1));

        cbFlightNo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(cbFlightNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 147, 270, -1));

        btnClear.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 264, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFlightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFlightKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtFlightKeyReleased

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtPriceKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<Flight> list = FlightDb.getallRecords();
        Iterator<Flight> itr = list.iterator();
        while(itr.hasNext()){
            Flight flightobj = itr.next();
            cbFlightNo.addItem(flightobj.getFlightNo());
            
        }
    }//GEN-LAST:event_formComponentShown

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        FlightDetails flightDetails = new FlightDetails();
        flightDetails.setFlightName(txtFlight.getText());
        flightDetails.setFlightNo((String)cbFlightNo.getSelectedItem());
        flightDetails.setPrice(txtPrice.getText());
        FlightDetailsDb.save(flightDetails);
        setVisible(false);
        new FlightDetailsProduct().setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new FlightDetailsProduct().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightDetailsProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbFlightNo;
    private javax.swing.JLabel lblFlight;
    private javax.swing.JLabel lblFlightDetails;
    private javax.swing.JLabel lblFlightNo;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JTextField txtFlight;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
