/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline_management;

import javax.swing.JOptionPane;

/**
 *
 * @author shreyasdasariicloud.com
 */
public class HomePage extends javax.swing.JFrame {
    public String email;

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }
    
    public HomePage(String userEmail) {
        initComponents();
        email = userEmail;
        if(!email.equals("admin@gmail.com")){
            btnFlight.setVisible(false);
            btnFlightDetails.setVisible(false);
//            btnViewFlight.setVisible(false);
            btnVerify.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnBookTicket = new javax.swing.JButton();
        btnBill = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnChangeSecQ = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnFlight = new javax.swing.JButton();
        btnFlightDetails = new javax.swing.JButton();
        btnEditFlight = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 38, -1, -1));

        btnBookTicket.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBookTicket.setText("Book Ticket");
        getContentPane().add(btnBookTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 38, -1, -1));

        btnBill.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBill.setText("View Bill & Booked Ticket Details");
        getContentPane().add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 38, -1, -1));

        btnChangePassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnChangePassword.setText("Change Password");
        getContentPane().add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 38, -1, -1));

        btnChangeSecQ.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnChangeSecQ.setText("Change Security Question");
        getContentPane().add(btnChangeSecQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 38, -1, -1));

        btnExit.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1189, 38, -1, -1));

        btnFlight.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnFlight.setText("Manage Flights");
        btnFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 720, -1, -1));

        btnFlightDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnFlightDetails.setText("Flight Details");
        btnFlightDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlightDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 720, -1, -1));

        btnEditFlight.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnEditFlight.setText("Edit Flight");
        btnEditFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFlightActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 720, -1, -1));

        btnVerify.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnVerify.setText("Verify Users");
        getContentPane().add(btnVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 720, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Logout?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new LoginJFrame().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Exit?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
            System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightActionPerformed
        // TODO add your handling code here:
        new ManageFlight().setVisible(true);
    }//GEN-LAST:event_btnFlightActionPerformed

    private void btnFlightDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightDetailsActionPerformed
        // TODO add your handling code here:
        new FlightDetailsProduct().setVisible(true);
    }//GEN-LAST:event_btnFlightDetailsActionPerformed

    private void btnEditFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFlightActionPerformed
        // TODO add your handling code here:
        new EditFlight().setVisible(true);
    }//GEN-LAST:event_btnEditFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnBookTicket;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangeSecQ;
    private javax.swing.JButton btnEditFlight;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFlight;
    private javax.swing.JButton btnFlightDetails;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
