/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline_management;

/**
 *
 * @author shreyasdasariicloud.com
 */
public class SignupJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignupJFrame
     */
    public SignupJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSignup = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblMobileno = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblSecQ = new javax.swing.JLabel();
        lblAnswer = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        txtMobileNo = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtSecQ = new javax.swing.JTextField();
        txtAnswer = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnForgetPass = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignup.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblSignup.setForeground(new java.awt.Color(0, 0, 255));
        lblSignup.setText("SignUp");
        getContentPane().add(lblSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 146, -1, -1));

        lblName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblName.setText("Name");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 224, -1, -1));

        lblEmailID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEmailID.setText("Email iD");
        getContentPane().add(lblEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 266, -1, -1));

        lblMobileno.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblMobileno.setText("Mobile No.");
        getContentPane().add(lblMobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 308, -1, -1));

        lblAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAddress.setText("Address");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 350, -1, -1));

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 392, -1, -1));

        lblSecQ.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSecQ.setText("Security Question");
        getContentPane().add(lblSecQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 434, -1, -1));

        lblAnswer.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAnswer.setText("Answer");
        getContentPane().add(lblAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 476, -1, -1));

        txtName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 221, 350, -1));

        txtEmailID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 263, 350, -1));

        txtMobileNo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 305, 350, -1));

        txtAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 347, 350, -1));

        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 389, 350, -1));

        txtSecQ.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtSecQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecQActionPerformed(evt);
            }
        });
        getContentPane().add(txtSecQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 431, 350, -1));

        txtAnswer.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 473, 350, -1));

        btnSave.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 543, -1, -1));

        btnClear.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 543, -1, -1));

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        jButton3.setText("Exit");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(906, 543, -1, -1));

        btnForgetPass.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnForgetPass.setText("Forget Password?");
        getContentPane().add(btnForgetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 608, -1, -1));

        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 608, -1, -1));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 38)); // NOI18N
        lblTitle.setText("ALPHA AIRLINE MANAGEMENT SYSTEM");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 62, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airplane 2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtSecQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnForgetPass;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblMobileno;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSecQ;
    private javax.swing.JLabel lblSignup;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSecQ;
    // End of variables declaration//GEN-END:variables
}
