/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline_management;

import common.OpenPDF;
import db.TicketDb;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Ticket;

/**
 *
 * @author shreyasdasariicloud.com
 */
public class ViewTicket extends javax.swing.JFrame {

    /**
     * Creates new form ViewTicket
     */
    public ViewTicket() {
        initComponents();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String todayDate = dFormat.format(date);
        txtFilterDate.setText(todayDate);

    }

    public void tableDetails() {
        String date = txtFilterDate.getText();
        String incDec = (String) cbTicketID.getSelectedItem();
        DefaultTableModel dtm = (DefaultTableModel) tblViewTicket.getModel();
        dtm.setRowCount(0);
        if (incDec.equals("ASCE")) {
            ArrayList<Ticket> list = TicketDb.getAllRecordsByInc(date);
            Iterator<Ticket> itr = list.iterator();
            while (itr.hasNext()) {
                Ticket ticketObj = itr.next();
                dtm.addRow(new Object[]{ticketObj.getId(), ticketObj.getName(), ticketObj.getMobileno(), ticketObj.getEmail(), ticketObj.getDate(), ticketObj.getTotal(), ticketObj.getCreatedBy(), ticketObj.getSource(), ticketObj.getDestination()});

            }
        } else {
            ArrayList<Ticket> list = TicketDb.getAllRecordsByDesc(date);
            Iterator<Ticket> itr = list.iterator();
            while (itr.hasNext()) {
                Ticket ticketObj = itr.next();
                dtm.addRow(new Object[]{ticketObj.getId(), ticketObj.getName(), ticketObj.getMobileno(), ticketObj.getEmail(), ticketObj.getDate(), ticketObj.getTotal(), ticketObj.getCreatedBy(), ticketObj.getSource(), ticketObj.getDestination()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFilterDate = new javax.swing.JLabel();
        txtFilterDate = new javax.swing.JTextField();
        lblTicketID = new javax.swing.JLabel();
        cbTicketID = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewTicket = new javax.swing.JTable();
        lblMessage = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTitle.setText("View Ticket Details");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblFilterDate.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFilterDate.setText("Filter By Date:");
        getContentPane().add(lblFilterDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 142, -1, -1));

        txtFilterDate.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtFilterDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterDateKeyReleased(evt);
            }
        });
        getContentPane().add(txtFilterDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 139, 250, -1));

        lblTicketID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTicketID.setText("Change Ticket By ID:");
        getContentPane().add(lblTicketID, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 142, -1, -1));

        cbTicketID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        cbTicketID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASCE", "DESC" }));
        cbTicketID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTicketIDActionPerformed(evt);
            }
        });
        getContentPane().add(cbTicketID, new org.netbeans.lib.awtextra.AbsoluteConstraints(993, 139, 250, -1));

        tblViewTicket.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        tblViewTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile No.", "Email", "Date", "Total", "CreatedBy", "Source", "Destination"
            }
        ));
        tblViewTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewTicketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewTicket);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 248, 1366, -1));

        lblMessage.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblMessage.setText("*Click on row to open the Ticket!");
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 713, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 710, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginJFrame().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFilterDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterDateKeyReleased
        // TODO add your handling code here:
        tableDetails();

    }//GEN-LAST:event_txtFilterDateKeyReleased

    private void cbTicketIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTicketIDActionPerformed
        // TODO add your handling code here:
        tableDetails();
    }//GEN-LAST:event_cbTicketIDActionPerformed

    private void tblViewTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewTicketMouseClicked
        // TODO add your handling code here:
        int index = tblViewTicket.getSelectedRow();
        TableModel model = tblViewTicket.getModel();
        String id = model.getValueAt(index, 0).toString();
        OpenPDF.openById(id);
        
    }//GEN-LAST:event_tblViewTicketMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        tableDetails();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cbTicketID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblFilterDate;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTicketID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblViewTicket;
    private javax.swing.JTextField txtFilterDate;
    // End of variables declaration//GEN-END:variables
}
